import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'sonner'
const MontSans = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SpaOzzy Web',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="es-AR">
        <body className={`${MontSans.variable} bg-slate-200/95 antialiased`}>
          {children}
          <Toaster position='top-center'/>
        </body>
      </html>
    </ClerkProvider>
  )
}
